### ISSUE TITLE
EasyPageComments

### ISSUE THREAD

**Issue by Lachiave** [Pomax/pomax.github.io#10]
I like it very EasyPageComments, but I would like to know how the admin can cancel a comment. Thank you

**Comment by Pomax** [comment]
The EasyPageComments repo is over on https://github.com/Pomax/EasyPageComments but be aware that it's a 7 year old solution for a version of PHP that no longer exists, so my recommendation would be to look for a newer, better solution first.

**Comment by Lachiave** [comment]
Thanks, but they are not easily found. You had done a really good job. It is a pity that you do not want to update it. Ciao

**Comment by Pomax** [comment]
It's not a matter of updating it: PHP has changed so much it would literally be writing something from scratch. Given that I haven't _used_ PHP for about six years now, in today's world I am not the person to write a new user management system for it

**Comment by Lachiave** [comment]
Anyway, you've been good. Ciao
