### ISSUE TITLE
For youre bugs in curves)

### ISSUE THREAD

**Issue by Wholemy** [Pomax/pomax.github.io#15]
https://github.com/Wholemy/PathSource
[Wholemy.BezTest.zip](https://github.com/Pomax/pomax.github.io/files/14119685/Wholemy.BezTest.zip)

If you need video: https://t.me/wholemy

Thank you for your code, I was able to improve my curve rendering at the expense of your code and achieve high performance when thickening curves) But you should think about it to improve your algorithm) I have attached the source code of the test application on the basis of which I was trying to improve the drawing of curves) It is written in C# in Visual Studio 2022)

**Comment by Pomax** [comment]
Thanks! I'll close this issue as it's not actually about any of the blog posts, but always nice to hear people found use in the content I write.
