### ISSUE TITLE
Knives Video

### ISSUE THREAD

**Issue by jothirams** [Pomax/pomax.github.io#2]
Hi Pomax,

I really liked your blog post about the Kitchen knives. I saw your other blog post - about the Youtube channel that you had started. It would be very helpful, if you can also make a video about how to use these knives in a video. Since we (I'm originally from India), never used so many different knives, I'm not able to relate to when/how to use these various knives. Thank you!

**Comment by Pomax** [comment]
Hey, sorry for never seeing this request - for some reason github didn't have me set to watch my own repo O_o!

It's an interesting idea, although would be hard to do as a single video as they're such diverse knives - I'd have to make a lot of different food at the same time to show them all off, so it might be better to do it as lots of small videos, but at that point there are already a lot of small videos like that on youtube, which you can find by searching for something like "how to use a ....." with the name of each knife/tool put in there.

**Comment by Pomax** [comment]
at this point, this is... not going to happen anymore >_>
