### ISSUE TITLE
Canon is misspelled as Cannon

### ISSUE THREAD

**Issue by enbo** [Pomax/Pomax.github.io#27]
Two instances in the article "We are really terrible at digital colours, and digital photography."

"used ot hearing them, and you might be thinking that an equivalent dSLR made by Nikon or Cannon, price wise, gets you a camera that"

"on par with the equivalent Nikon or Cannon. And if they start losing money, it's a good bet someone like Nikon or Canon will buy them."

**Comment by Pomax** [comment]
:boom: let's fix that. Thanks for letting me know!

**Comment by Pomax** [comment]
fixed!

**Comment by enbo** [comment]
I just realized there was another typo. In the first example above, it should be "used to hearing" not "used ot hearing".

**Comment by Pomax** [comment]
fixed as well, thanks!
