### ISSUE TITLE
Self-intersecting Bézier

### ISSUE THREAD

**Issue by hytti** [Pomax/pomax.github.io#6]
https://github.com/Pomax/BezierInfo-2/issues/117

**Comment by Pomax** [comment]
While I appreciate the comment, I'm a bit puzzled why you wrote it as a comment to my blog site, rather than as a comment in the repository for the Primer on Bezier curves, which would seem a much more logical place for this kind of information (and possibly resulting discussion)

**Comment by hytti** [comment]
you are absolutely right, this is strange route to comment on your primer. as a private person i had already written this comment and tried to email it to an address that probably is defunct by now. as a "letter" it seemed too long for a comment thread with its personal introduction. plus that i am not all that comfortable with the idea of using disqus. sorry for being such a square.

**Comment by Pomax** [comment]
if you sent it to my email address as listed in my github profile, you sent it to the right place. Also I didn't say disqus: the primer has its of github repository, with issue tracker, exactly for this kind of discussion.

https://github.com/pomax/BezierInfo-2/issues

**Comment by hytti** [comment]
relocated: [Self-intersecting Bézier #117](https://github.com/Pomax/BezierInfo-2/issues/117).

this issue can probably be closed (and deleted?)

**Comment by Pomax** [comment]
there's no delete on github, but I can delete all our follow-up comments and then blank the first one if you like.

**Comment by hytti** [comment]
that would be kind. there's probably need to archive this "tutorial". &lt;insert appropriate emoji&gt;

will the tschirnhausen family portrait need to be re-uploaded to the relocated issue if the link in this original thread is removed? i'll fix the link in issue #117 if needed.

**Comment by Pomax** [comment]
pretty sure that'll remain, but let's find out: I'll remove all our comments and blank the original issue with just the link to the "Real" one.
