### ISSUE TITLE
blog link not redirecting properly

### ISSUE THREAD

**Issue by howardck** [Pomax/pomax.github.io#7]
There's a link in your blog entry "Localization is hard" that isn't working correctly. The pseudo-link "background in Japanese" about 80% of the way down the page should redirect to https://pomax.github.com/NRGrammar but instead returns a 'Post redirection' notification that says the redirect will fail if JavaScript is disabled. JavaScript isn't disabled on my machine however. I've tried both Chrome and Safari (MacOS).

FWIW I see you're on Vancouver Island, a nice place to live. I'm not that far across the water from you on the Sunshine Coast.

**Comment by Pomax** [comment]
Good catch, that should have been http://pomax.github.io/nrGrammar (yay, casing). Fixed.

Also, the part of Vancouver Island I'm on is not so nice at the moment, the sky is 50% smoke.

**Comment by howardck** [comment]
That works better. Quick fix! 

Smoke's bad here too. Where on the Island, if you don't mind my asking? I've lived in both Ladysmith and Nanaimo and have spent a bunch of time in the Courtenay area as well. Fond memories of all.

**Comment by Pomax** [comment]
Between Somenos and Quamichan lakes. There was a fire on Maple Mountain as well, which didn't help.
