### ISSUE TITLE
A pan for steaming the oven

### ISSUE THREAD

**Issue by ptrktn** [Pomax/pomax.github.io#8]
Hi,

The article on making French baguettes is great, thank you very much. I'll be using it as a reference material in my more advanced kitchen experiments.

There was a note about using a pan at the base of the oven for steaming. Rather than using an actual pan, one could potentially utilise an improvised container made from a sheet of aluminium foil.

Thanks and have a nice day.

Petteri

**Comment by Pomax** [comment]
the problem with aluminium foil is that it will react with the water. Not a lot, but at that temperature your foil will go in "shiny" and come out "brown", so you typically want to use something that you know is 100% entirely nonreactive. Also, if you're making baguettes, generally it's a good idea to make sure your setup is repeatable, for which you don't really want makeshift solutions that you have to recraft every batch.

**Comment by ptrktn** [comment]
Good point about aluminium, thanks.
